all:
	g++ -std=c++17 -Wall -Wextra -pedantic -O3 500.cpp -o ../bin/2d_500
	g++ -std=c++17 -Wall -Wextra -pedantic -O3 1000.cpp -o ../bin/2d_1000
	g++ -std=c++17 -Wall -Wextra -pedantic -O3 2000.cpp -o ../bin/2d_2000
	g++ -std=c++17 -Wall -Wextra -pedantic -O3 5000.cpp -o ../bin/2d_5000
